name: Laravel prod
on: 
  pull_request:
    types: [closed]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build . -t 2851997/laravel-test
      - name: Login to docker hub
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - name: Push docker image
        run: docker push 2851997/laravel-test